baseURL = "https://<tu-usuario>.github.io/<tu-repo>/"
languageCode = "en"
title = "Santiago Moreno"
# theme = ""  # vac√≠o si usas tus propios layouts

[menu]

  [[menu.main]]
    name   = "CV"
    url    = "/cv/"
    weight = 10

  [[menu.main]]
    name   = "Education"
    url    = "/education/"
    weight = 20

  [[menu.main]]
    name   = "Personal Development"
    url    = "/personal-development/"
    weight = 30

  [[menu.main]]
    name   = "Other Interests & Skills"
    url    = "/other-interests/"
    weight = 40

  [[menu.main]]
    name   = "Astrology"
    url    = "/astrology/"
    weight = 50